// ==UserScript==
// @name        Webcomic Keyboard Shortcuts
// @namespace   samuelphillips.net
// @description Keyboard shortcuts for multiple sites, including El Goonish Shrive, Will Save World for Gold, General Protection Fault, Gunnerkrigg Count, Fanboys Online, Manga Reader.net, Saturday Morning Breakfast Cereal, Order of the Stick.
// @include     http://www.egscomics.com/*
// @include     https://www.egscomics.com/*
// @include     http://willsaveworldforgold.com/*
// @include     https://willsaveworldforgold.com/*
// @include     http://www.gpf-comics.com/*
// @include     https://www.gpf-comics.com/*
// @include     http://www.gunnerkrigg.com/*
// @include     https://www.gunnerkrigg.com/*
// @include     http://fanboys-online.com/*
// @include     https://fanboys-online.com/*
// @include     http://mangareader.net/*
// @include     https://mangareader.net/*
// @include     http://www.smbc-comics.com/*
// @include     https://www.smbc-comics.com/*
// @include     http://www.giantitp.com/*
// @include     https://www.giantitp.com/*
// @require     http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
// @version     1
// @grant       none
// ==/UserScript==

const site_conf = {"fanboys-online.com": {"prev": ".prev", "next": ".next", "parenting": [0, 0], "name": "Fanboys Online"}, "www.egscomics.com": {"prev": ".prev", "next": ".next", "parenting": [0, 0], "name": "El Goonish Shrive"}, "willsaveworldforgold.com": {"prev": ".navi-prev", "next": ".navi-next", "parenting": [0, 0], "name": "Will Save World for Gold"}, "www.gpf-comics.com": {"prev": ".nav_link_back a:last-child", "next": ".nav_link_forward a:first-child", "parenting": [0, 0], "name": "General Protection Fault"}, "www.giantitp.com": {"prev": "a > img[alt=\"Previous Comic\"]", "next": "a > img[alt=\"Next Comic\"]", "parenting": [1, 1], "name": "Order of the Stick"}, "mangareader.net": {"prev": ".prev", "next": ".next", "parenting": [0, 0], "name": "Manga Reader.net"}, "www.smbc-comics.com": {"prev": "a.prev", "next": "a.next", "parenting": [0, 0], "name": "Saturday Morning Breakfast Cereal"}, "www.gunnerkrigg.com": {"prev": ".extra .nav .left", "next": ".extra .nav .right", "parenting": [0, 0], "name": "Gunnerkrigg Count"}};

// Generated by LiveScript 1.5.0
(function(){
  var KEY_CODE_LEFT, KEY_CODE_RIGHT, sitecfg;
  KEY_CODE_LEFT = 37;
  KEY_CODE_RIGHT = 39;
  sitecfg = site_conf[window.location.hostname];
  $(function(){
    var next, prev, i$, to$, _;
    next = document.querySelector(sitecfg.next);
    prev = document.querySelector(sitecfg.prev);
    for (i$ = 0, to$ = sitecfg.parenting[0]; i$ < to$; ++i$) {
      _ = i$;
      next = next.parentElement;
    }
    for (i$ = 0, to$ = sitecfg.parenting[1]; i$ < to$; ++i$) {
      _ = i$;
      prev = prev.parentElement;
    }
    $(window).keydown(function(e){
      if (prev != null && e.keyCode === KEY_CODE_LEFT) {
        e.preventDefault();
        location.href = prev.href;
      } else if (next != null && e.keyCode === KEY_CODE_RIGHT) {
        console.log("moving fwd");
        e.preventDefault();
        location.href = next.href;
      }
    });
    console.log("Webcomic Keyboard Shortcuts enabled; " + ("this site hosts " + sitecfg.name));
    if (next == null) {
      console.log("Will not be able to move forward on this page");
    }
    if (prev == null) {
      console.log("Will not be able to move backwards on this page");
    }
  });
}).call(this);
