// ==UserScript==
// @name        Webcomic Keyboard Shortcuts
// @namespace   samuelphillips.net
// @description Keyboard shortcuts for multiple sites, including Spacetrawler, El Goonish Shrive, Will Save World for Gold, General Protection Fault, Gunnerkrigg Court, Fanboys Online, Manga Reader.net, Saturday Morning Breakfast Cereal, Order of the Stick, Drive, Cyanide & Happiness.
// @include     http://www.baldwinpage.com/*
// @include     https://www.baldwinpage.com/*
// @include     http://www.egscomics.com/*
// @include     https://www.egscomics.com/*
// @include     http://willsaveworldforgold.com/*
// @include     https://willsaveworldforgold.com/*
// @include     http://www.gpf-comics.com/*
// @include     https://www.gpf-comics.com/*
// @include     http://www.gunnerkrigg.com/*
// @include     https://www.gunnerkrigg.com/*
// @include     http://fanboys-online.com/*
// @include     https://fanboys-online.com/*
// @include     http://mangareader.net/*
// @include     https://mangareader.net/*
// @include     http://www.smbc-comics.com/*
// @include     https://www.smbc-comics.com/*
// @include     http://www.giantitp.com/*
// @include     https://www.giantitp.com/*
// @include     http://www.drivecomic.com/*
// @include     https://www.drivecomic.com/*
// @include     http://explosm.net/*
// @include     https://explosm.net/*
// @require     http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
// @version     1.3
// @grant       none
// ==/UserScript==

const site_conf = {"www.baldwinpage.com": {"parenting": [0, 0], "next": "a[rel=next]", "name": "Spacetrawler", "prev": "a[rel=prev]"}, "www.gpf-comics.com": {"parenting": [0, 0], "next": ".nav_link_forward a:first-child", "name": "General Protection Fault", "prev": ".nav_link_back a:last-child"}, "explosm.net": {"parenting": [0, 0], "next": "a.next-comic", "name": "Cyanide & Happiness", "prev": "a.previous-comic"}, "mangareader.net": {"parenting": [0, 0], "next": ".next", "name": "Manga Reader.net", "prev": ".prev"}, "www.drivecomic.com": {"parenting": [0, 0], "next": "#comic-next a", "name": "Drive", "prev": "#comic-previous a"}, "www.smbc-comics.com": {"parenting": [0, 0], "next": "a.next", "name": "Saturday Morning Breakfast Cereal", "prev": "a.prev"}, "willsaveworldforgold.com": {"parenting": [0, 0], "next": ".navi-next", "name": "Will Save World for Gold", "prev": ".navi-prev"}, "www.giantitp.com": {"parenting": [1, 1], "next": "a > img[alt=\"Next Comic\"]", "name": "Order of the Stick", "prev": "a > img[alt=\"Previous Comic\"]"}, "www.gunnerkrigg.com": {"parenting": [0, 0], "next": ".extra .nav .right", "name": "Gunnerkrigg Court", "prev": ".extra .nav .left"}, "www.egscomics.com": {"parenting": [0, 0], "next": ".next", "name": "El Goonish Shrive", "prev": ".prev"}, "fanboys-online.com": {"parenting": [0, 0], "next": ".next", "name": "Fanboys Online", "prev": ".prev"}};

// Generated by LiveScript 1.5.0
(function(){
  var KEY_CODE_LEFT, KEY_CODE_RIGHT, sitecfg;
  KEY_CODE_LEFT = 37;
  KEY_CODE_RIGHT = 39;
  sitecfg = site_conf[window.location.hostname];
  $(function(){
    var next, prev, i$, to$, _;
    next = document.querySelector(sitecfg.next);
    prev = document.querySelector(sitecfg.prev);
    for (i$ = 0, to$ = sitecfg.parenting[0]; i$ < to$; ++i$) {
      _ = i$;
      next = next.parentElement;
    }
    for (i$ = 0, to$ = sitecfg.parenting[1]; i$ < to$; ++i$) {
      _ = i$;
      prev = prev.parentElement;
    }
    $(window).keydown(function(e){
      if (prev != null && e.keyCode === KEY_CODE_LEFT) {
        e.preventDefault();
        location.href = prev.href;
      } else if (next != null && e.keyCode === KEY_CODE_RIGHT) {
        console.log("moving fwd");
        e.preventDefault();
        location.href = next.href;
      }
    });
    console.log("Webcomic Keyboard Shortcuts enabled; " + ("this site hosts " + sitecfg.name));
    if (next == null) {
      console.log("Will not be able to move forward on this page");
    }
    if (prev == null) {
      console.log("Will not be able to move backwards on this page");
    }
  });
}).call(this);
